## Modifying Values In A Dataframe

In [27]:
import pandas as pd

In [28]:
hero  = pd.read_pickle('hero.pkl')

In [29]:
# Notice dashes in some columns
hero.head(5)

,name,gender,eye color,race,hair color,height,publisher,alignment,weight,hero names,...,web creation,reality warping,odin force,symbiote costume,speed force,phoenix force,molecular dissipation,vision - cryo,omnipresent,omniscient
0,Abin Sur,Male,blue,Ungaran,No Hair,185,DC Comics,good,90.0,Abin Sur,...,False,False,False,False,False,False,False,False,False,False
1,Adam Strange,Male,blue,Human,Blond,185,DC Comics,good,88.0,Adam Strange,...,False,False,False,False,False,False,False,False,False,False
2,Alan Scott,Male,blue,-,Blond,180,DC Comics,good,90.0,Alan Scott,...,False,False,False,False,False,False,False,False,False,False
3,Amazo,Male,red,Android,-,257,DC Comics,bad,173.0,Amazo,...,False,False,False,False,False,False,False,False,False,False
4,Animal Man,Male,blue,Human,Blond,183,DC Comics,good,83.0,Animal Man,...,False,False,False,False,False,False,False,False,False,False

### Change Columns

In [30]:
hero.loc[2,'race']

'-'

In [31]:
hero.loc[2,'race'] = 'Unknown'

In [32]:
# Alan Scott's race is now 'Unknown'
hero.head()

,name,gender,eye color,race,hair color,height,publisher,alignment,weight,hero names,...,web creation,reality warping,odin force,symbiote costume,speed force,phoenix force,molecular dissipation,vision - cryo,omnipresent,omniscient
0,Abin Sur,Male,blue,Ungaran,No Hair,185,DC Comics,good,90.0,Abin Sur,...,False,False,False,False,False,False,False,False,False,False
1,Adam Strange,Male,blue,Human,Blond,185,DC Comics,good,88.0,Adam Strange,...,False,False,False,False,False,False,False,False,False,False
2,Alan Scott,Male,blue,Unknown,Blond,180,DC Comics,good,90.0,Alan Scott,...,False,False,False,False,False,False,False,False,False,False
3,Amazo,Male,red,Android,-,257,DC Comics,bad,173.0,Amazo,...,False,False,False,False,False,False,False,False,False,False
4,Animal Man,Male,blue,Human,Blond,183,DC Comics,good,83.0,Animal Man,...,False,False,False,False,False,False,False,False,False,False

In [33]:
hero.iloc[2,3] = '-'

In [34]:
# Changed back to - 
hero.head()

,name,gender,eye color,race,hair color,height,publisher,alignment,weight,hero names,...,web creation,reality warping,odin force,symbiote costume,speed force,phoenix force,molecular dissipation,vision - cryo,omnipresent,omniscient
0,Abin Sur,Male,blue,Ungaran,No Hair,185,DC Comics,good,90.0,Abin Sur,...,False,False,False,False,False,False,False,False,False,False
1,Adam Strange,Male,blue,Human,Blond,185,DC Comics,good,88.0,Adam Strange,...,False,False,False,False,False,False,False,False,False,False
2,Alan Scott,Male,blue,-,Blond,180,DC Comics,good,90.0,Alan Scott,...,False,False,False,False,False,False,False,False,False,False
3,Amazo,Male,red,Android,-,257,DC Comics,bad,173.0,Amazo,...,False,False,False,False,False,False,False,False,False,False
4,Animal Man,Male,blue,Human,Blond,183,DC Comics,good,83.0,Animal Man,...,False,False,False,False,False,False,False,False,False,False

### Change Whole Column

In [50]:
hero.loc[(hero['race'] == '-'),'race']

2      -
6      -
11     -
12     -
13     -
      ..
526    -
527    -
529    -
531    -
533    -
Name: race, Length: 193, dtype: string

In [51]:
#Reset dataframe for testing
hero  = pd.read_pickle('hero.pkl')
hero.loc[hero['race'] == '-','race'] = 'Unknown'

In [52]:
hero.loc[(hero['race'] == 'Unknown'),'race']

2      Unknown
6      Unknown
11     Unknown
12     Unknown
13     Unknown
        ...
526    Unknown
527    Unknown
529    Unknown
531    Unknown
533    Unknown
Name: race, Length: 193, dtype: string

### Add Rows

In [54]:
hero.loc[533]

name                     X-Man
gender                    Male
eye color                 blue
race                         -
hair color               Brown
                         ...
phoenix force            False
molecular dissipation    False
vision - cryo            False
omnipresent              False
omniscient               False
Name: 533, Length: 177, dtype: object

In [55]:
hero.shape

(537, 177)

In [59]:
hero.loc[10000]=hero.loc[533]

In [57]:
hero.shape

(538, 177)

In [58]:
## Cannot do with .iloc
hero.tail()

,name,gender,eye color,race,hair color,height,publisher,alignment,weight,hero names,...,web creation,reality warping,odin force,symbiote costume,speed force,phoenix force,molecular dissipation,vision - cryo,omnipresent,omniscient
533,X-Man,Male,blue,-,Brown,175,Marvel Comics,good,61.0,X-Man,...,False,False,False,False,False,False,False,False,False,False
534,Yellowjacket,Male,blue,Human,Blond,183,Marvel Comics,good,83.0,Yellowjacket,...,False,False,False,False,False,False,False,False,False,False
535,Yellowjacket II,Female,blue,Human,Strawberry Blond,165,Marvel Comics,good,52.0,Yellowjacket II,...,False,False,False,False,False,False,False,False,False,False
536,Ymir,Male,white,Frost Giant,No Hair,305,Marvel Comics,good,-99.0,Ymir,...,False,False,False,False,False,False,False,False,False,False
10000,X-Man,Male,blue,-,Brown,175,Marvel Comics,good,61.0,X-Man,...,False,False,False,False,False,False,False,False,False,False

In [62]:
## We can replace with .iloc however.See 533 and 536 are the same
hero.iloc[536] = hero.iloc[533]
hero.tail()

,name,gender,eye color,race,hair color,height,publisher,alignment,weight,hero names,...,web creation,reality warping,odin force,symbiote costume,speed force,phoenix force,molecular dissipation,vision - cryo,omnipresent,omniscient
533,X-Man,Male,blue,-,Brown,175,Marvel Comics,good,61.0,X-Man,...,False,False,False,False,False,False,False,False,False,False
534,Yellowjacket,Male,blue,Human,Blond,183,Marvel Comics,good,83.0,Yellowjacket,...,False,False,False,False,False,False,False,False,False,False
535,Yellowjacket II,Female,blue,Human,Strawberry Blond,165,Marvel Comics,good,52.0,Yellowjacket II,...,False,False,False,False,False,False,False,False,False,False
536,X-Man,Male,blue,-,Brown,175,Marvel Comics,good,61.0,X-Man,...,False,False,False,False,False,False,False,False,False,False
10000,X-Man,Male,blue,-,Brown,175,Marvel Comics,good,61.0,X-Man,...,False,False,False,False,False,False,False,False,False,False

### Change column

In [63]:
# This is in cm, we want inches
hero['height']

0        185
1        185
2        180
3        257
4        183
        ...
533      175
534      183
535      165
536      175
10000    175
Name: height, Length: 538, dtype: int64

In [64]:
hero['height']*0.0328084

0        6.069554
1        6.069554
2        5.905512
3        8.431759
4        6.003937
           ...
533      5.741470
534      6.003937
535      5.413386
536      5.741470
10000    5.741470
Name: height, Length: 538, dtype: float64

In [65]:
hero['height'] = hero['height']*0.0328084

In [66]:
hero['height']

0        6.069554
1        6.069554
2        5.905512
3        8.431759
4        6.003937
           ...
533      5.741470
534      6.003937
535      5.413386
536      5.741470
10000    5.741470
Name: height, Length: 538, dtype: float64

### Change all columns with numbers in dataframe

In [73]:
# Same as hero[['height','weight']] but there could be more numeric columns so a lot of typing hence select_dtypes
hero.select_dtypes(include='number')

         height  weight
0      6.069554    90.0
1      6.069554    88.0
2      5.905512    90.0
3      8.431759   173.0
4      6.003937    83.0
...         ...     ...
533    5.741470    61.0
534    6.003937    83.0
535    5.413386    52.0
536    5.741470    61.0
10000  5.741470    61.0

[538 rows x 2 columns]

In [70]:
numeric_cols = hero.select_dtypes(include='number').columns

In [71]:
numeric_cols

Index(['height', 'weight'], dtype='object')

In [75]:
## Now with the numeric_cols above we have easy access to the numeric columns
hero[numeric_cols]

         height  weight
0      6.069554    90.0
1      6.069554    88.0
2      5.905512    90.0
3      8.431759   173.0
4      6.003937    83.0
...         ...     ...
533    5.741470    61.0
534    6.003937    83.0
535    5.413386    52.0
536    5.741470    61.0
10000  5.741470    61.0

[538 rows x 2 columns]

In [76]:
## Can now multiply by 100 or do as desired to numeric columns
hero[numeric_cols] = hero[numeric_cols]*100

In [77]:
hero[numeric_cols]

          height   weight
0      606.95540   9000.0
1      606.95540   8800.0
2      590.55120   9000.0
3      843.17588  17300.0
4      600.39372   8300.0
...          ...      ...
533    574.14700   6100.0
534    600.39372   8300.0
535    541.33860   5200.0
536    574.14700   6100.0
10000  574.14700   6100.0

[538 rows x 2 columns]

In [80]:
# Change back
hero[numeric_cols] = hero[numeric_cols]/100

In [81]:
hero[numeric_cols]

         height  weight
0      0.060696    0.90
1      0.060696    0.88
2      0.059055    0.90
3      0.084318    1.73
4      0.060039    0.83
...         ...     ...
533    0.057415    0.61
534    0.060039    0.83
535    0.054134    0.52
536    0.057415    0.61
10000  0.057415    0.61

[538 rows x 2 columns]

### Add new column to dataframe

In [ ]:
## We want BMI = weight / height(m)^2

In [84]:
hero['weight']/(hero['height']/3.28084)**2

0        2629.656684
1        2571.219869
2        2777.777778
3        2619.267514
4        2478.425752
            ...
533      1991.836735
534      2478.425752
535      1910.009183
536      1991.836735
10000    1991.836735
Length: 538, dtype: float64

In [86]:
hero['bmi'] = hero['weight']/(hero['height']/3.28084)**2

In [87]:
## bmi has been added
hero.columns

Index(['name', 'gender', 'eye color', 'race', 'hair color', 'height',
       'publisher', 'alignment', 'weight', 'hero names',
       ...
       'reality warping', 'odin force', 'symbiote costume', 'speed force',
       'phoenix force', 'molecular dissipation', 'vision - cryo',
       'omnipresent', 'omniscient', 'bmi'],
      dtype='object', length=178)

In [88]:
hero.head()

,name,gender,eye color,race,hair color,height,publisher,alignment,weight,hero names,...,reality warping,odin force,symbiote costume,speed force,phoenix force,molecular dissipation,vision - cryo,omnipresent,omniscient,bmi
0,Abin Sur,Male,blue,Ungaran,No Hair,0.060696,DC Comics,good,0.90,Abin Sur,...,False,False,False,False,False,False,False,False,False,2629.656684
1,Adam Strange,Male,blue,Human,Blond,0.060696,DC Comics,good,0.88,Adam Strange,...,False,False,False,False,False,False,False,False,False,2571.219869
2,Alan Scott,Male,blue,-,Blond,0.059055,DC Comics,good,0.90,Alan Scott,...,False,False,False,False,False,False,False,False,False,2777.777778
3,Amazo,Male,red,Android,-,0.084318,DC Comics,bad,1.73,Amazo,...,False,False,False,False,False,False,False,False,False,2619.267514
4,Animal Man,Male,blue,Human,Blond,0.060039,DC Comics,good,0.83,Animal Man,...,False,False,False,False,False,False,False,False,False,2478.425752