## Subsetting Rows and Columns

In [1]:
import pandas as pd

In [2]:
hero = pd.read_pickle('hero.pkl')

In [4]:
hero.head(5)

,name,gender,eye color,race,hair color,height,publisher,alignment,weight,hero names,...,web creation,reality warping,odin force,symbiote costume,speed force,phoenix force,molecular dissipation,vision - cryo,omnipresent,omniscient
0,Abin Sur,Male,blue,Ungaran,No Hair,185,DC Comics,good,90.0,Abin Sur,...,False,False,False,False,False,False,False,False,False,False
1,Adam Strange,Male,blue,Human,Blond,185,DC Comics,good,88.0,Adam Strange,...,False,False,False,False,False,False,False,False,False,False
2,Alan Scott,Male,blue,-,Blond,180,DC Comics,good,90.0,Alan Scott,...,False,False,False,False,False,False,False,False,False,False
3,Amazo,Male,red,Android,-,257,DC Comics,bad,173.0,Amazo,...,False,False,False,False,False,False,False,False,False,False
4,Animal Man,Male,blue,Human,Blond,183,DC Comics,good,83.0,Animal Man,...,False,False,False,False,False,False,False,False,False,False

In [6]:
#null slice, gets all columns. Same as this hero.loc[0]
hero.loc[0,:]

name                     Abin Sur
gender                       Male
eye color                    blue
race                      Ungaran
hair color                No Hair
                           ...
phoenix force               False
molecular dissipation       False
vision - cryo               False
omnipresent                 False
omniscient                  False
Name: 0, Length: 177, dtype: object

In [7]:
hero.loc[0,'race']

'Ungaran'

In [9]:
hero.iloc[0,3]

'Ungaran'

In [10]:
#hero.loc[2:4,'race':'height'] also works
hero.loc[2:4,['race','hair color','height']]

      race hair color  height
2        -      Blond     180
3  Android          -     257
4    Human      Blond     183

In [11]:
hero.iloc[2:5,3:6]

      race hair color  height
2        -      Blond     180
3  Android          -     257
4    Human      Blond     183

In [14]:
hero.loc[10:20,['hero names','super strength','flight','super speed']]

   hero names  super strength  flight  super speed
10      Atlas            True   False         True
11       Atom            True   False         True
12       Atom            True   False         True
13  Atom Girl           False   False        False
14    Atom II            True    True        False
15   Atom III           False   False        False
16    Atom IV           False   False        False
17     Azrael            True   False         True
18      Aztar            True    True         True
19       Bane            True   False         True
20    Batgirl           False   False        False

In [15]:
hero.iloc[10:21,[9,27,18,40]]

   hero names  super strength  flight  super speed
10      Atlas            True   False         True
11       Atom            True   False         True
12       Atom            True   False         True
13  Atom Girl           False   False        False
14    Atom II            True    True        False
15   Atom III           False   False        False
16    Atom IV           False   False        False
17     Azrael            True   False         True
18      Aztar            True    True         True
19       Bane            True   False         True
20    Batgirl           False   False        False

In [19]:
hero.loc[hero['flight'] == True,'name']

1         Adam Strange
2           Alan Scott
3                Amazo
5         Anti-Monitor
14             Atom II
            ...
525               Wasp
526            Watcher
531         Wonder Man
533              X-Man
535    Yellowjacket II
Name: name, Length: 197, dtype: string

In [20]:
mask = hero['flight'] == True
hero.iloc[mask.values,0]

1         Adam Strange
2           Alan Scott
3                Amazo
5         Anti-Monitor
14             Atom II
            ...
525               Wasp
526            Watcher
531         Wonder Man
533              X-Man
535    Yellowjacket II
Name: name, Length: 197, dtype: string

In [23]:
## This works to filter flight but to get all columns. You can't easily just get the 'name' column in this single statement, unlike above with iloc and loc
hero[hero['flight']==True]

,name,gender,eye color,race,hair color,height,publisher,alignment,weight,hero names,...,web creation,reality warping,odin force,symbiote costume,speed force,phoenix force,molecular dissipation,vision - cryo,omnipresent,omniscient
1,Adam Strange,Male,blue,Human,Blond,185,DC Comics,good,88.0,Adam Strange,...,False,False,False,False,False,False,False,False,False,False
2,Alan Scott,Male,blue,-,Blond,180,DC Comics,good,90.0,Alan Scott,...,False,False,False,False,False,False,False,False,False,False
3,Amazo,Male,red,Android,-,257,DC Comics,bad,173.0,Amazo,...,False,False,False,False,False,False,False,False,False,False
5,Anti-Monitor,Male,yellow,God / Eternal,No Hair,61,DC Comics,bad,NaN,Anti-Monitor,...,False,True,False,False,False,False,False,False,False,False
14,Atom II,Male,brown,Human,Auburn,183,DC Comics,good,81.0,Atom II,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,Wasp,Female,blue,Human,Auburn,163,Marvel Comics,good,50.0,Wasp,...,False,False,False,False,False,False,False,False,False,False
526,Watcher,Male,-,-,-,-99,Marvel Comics,good,-99.0,Watcher,...,False,False,False,False,False,False,False,False,False,False
531,Wonder Man,Male,red,-,Black,188,Marvel Comics,good,171.0,Wonder Man,...,False,False,False,False,False,False,False,False,False,False
533,X-Man,Male,blue,-,Brown,175,Marvel Comics,good,61.0,X-Man,...,False,False,False,False,False,False,False,False,False,False
535,Yellowjacket II,Female,blue,Human,Strawberry Blond,165,Marvel Comics,good,52.0,Yellowjacket II,...,False,False,False,False,False,False,False,False,False,False

In [24]:
# Same as hero['name']
hero.loc[:,'name']

0             Abin Sur
1         Adam Strange
2           Alan Scott
3                Amazo
4           Animal Man
            ...
532               X-23
533              X-Man
534       Yellowjacket
535    Yellowjacket II
536               Ymir
Name: name, Length: 537, dtype: string