# groupby()

#### Group by is a process involving 3 steps:
##### 1) Split the data into groups based on criteria
##### 2) Apply a function to each group independently
##### 3) Cpmbine the results into a data structure

## Imports and data

In [9]:
import pandas as pd

In [12]:
air_quality = pd.read_pickle('air_quality.pkl')

In [14]:
air_quality.head()

,date_time,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,...,hour,quarter,day_of_week_num,day_of_week_name,time_until_2022,time_until_2022_days,time_until_2022_weeks,prior_2016_ind,PM2.5_category,TEMP_category
0,2013-03-01 00:00:00,9.0,9.0,3.0,17.0,300.0,89.0,-0.5,1024.5,-21.4,...,0,1,4,Friday,3228 days 00:00:00,3228.000000,461.142857,True,Good,Very Cold
1,2013-03-01 01:00:00,4.0,4.0,3.0,16.0,300.0,88.0,-0.7,1025.1,-22.1,...,1,1,4,Friday,3227 days 23:00:00,3227.958333,461.136905,True,Good,Very Cold
2,2013-03-01 05:00:00,4.0,4.0,9.0,25.0,300.0,78.0,-2.4,1027.5,-21.3,...,5,1,4,Friday,3227 days 19:00:00,3227.791667,461.113095,True,Good,Very Cold
3,2013-03-01 06:00:00,5.0,5.0,10.0,29.0,400.0,67.0,-2.5,1028.2,-20.4,...,6,1,4,Friday,3227 days 18:00:00,3227.750000,461.107143,True,Good,Very Cold
4,2013-03-01 07:00:00,3.0,6.0,12.0,40.0,400.0,52.0,-1.4,1029.5,-20.4,...,7,1,4,Friday,3227 days 17:00:00,3227.708333,461.101190,True,Good,Very Cold

## groupby() Basics

In [19]:
## In this example we are grouping the air_quality dataframe by PM2.5_category
## BUT does not display anything outside of the notification that they are grouped.
## See next cell
air_quality.groupby(by='PM2.5_category').

C:\Users\jakeb\AppData\Local\Temp\ipykernel_11152\1346724448.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  air_quality.groupby(by='PM2.5_category')

In [23]:
## using .group we can see a dictonary whos keys are the categories and the values are the rows axis lables they apply to
air_quality.groupby(by='PM2.5_category').groups

C:\Users\jakeb\AppData\Local\Temp\ipykernel_11152\968027210.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  air_quality.groupby(by='PM2.5_category').groups

{'Good': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 72, 73, 74, 75, 76, 78, 81, 82, 83, 168, 169, 201, 202, 203, 205, 206, 208, 238, 275, 276, 277, 278, 282, 283, 286, 287, 370, 371, 411, 412, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 462, 463, 464, 465, 466, 467, 468, 495, 507, 513, 514, 515, 520, 521, 522, 523, 524, 525, 527, 528, 529, 534, 535, 536, 624, 636, 637, 638, ...], 'Moderate': [16, 18, 19, 28, 33, 34, 35, 36, 61, 71, 77, 79, 80, 84, 85, 86, 87, 196, 197, 198, 199, 200, 204, 207, 209, 210, 211, 212, 213, 214, 215, 216, 217, 279, 280, 281, 284, 285, 288, 289, 290, 292, 410, 446, 447, 461, 469, 470, 512, 516, 517, 518, 519, 526, 530, 531, 532, 533, 537, 538, 623, 625, 626, 629, 630, 631, 632, 633, 634, 635, 719, 720, 721, 722, 723, 727, 736, 737, 738, 739, 747, 748, 749, 750, 751, 752, 779, 780, 783, 784, 785, 786, 787, 788, 789, 791, 792, 793, 794, 795, ...], 'Unhealthy for sensitive groups': [37, 38, 60, 62, 88, 89, 178, 183, 184, 193, 194, 195, 218, 219, 220, 221, 274, 291, 293, 294, 372, 373, 429, 430, 431, 432, 433, 434, 435, 436, 437, 539, 627, 628, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 717, 718, 753, 776, 777, 778, 781, 782, 868, 869, 870, 871, 872, 876, 877, 878, 879, 882, 883, 886, 903, 904, 926, 927, 928, 929, 930, 939, 940, 941, 959, 961, 962, 965, 974, 985, 988, 989, 990, 991, 992, 993, 994, 1004, 1005, 1006, 1026, 1027, 1028, 1031, 1032, 1033, 1034, 1035, ...], 'Unhealthy': [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 63, 64, 65, 67, 68, 69, 70, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 123, 167, 172, 177, 179, 180, 181, 182, 185, 186, 187, 188, 189, 190, 192, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 239, 240, 241, 242, 243, 244, 245, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 264, 265, 266, 267, 268, 269, 270, 271, 272, ...], 'Very unhealthy': [66, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 138, 140, 141, 142, 143, 153, 154, 155, 156, 157, 171, 173, 174, 176, 191, 246, 247, 262, 263, 318, 319, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 365, 366, 367, 368, 369, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 408, ...], 'Hazardous': [137, 139, 144, 145, 146, 147, 148, 149, 150, 151, 152, 158, 159, 160, 161, 162, 163, 164, 165, 166, 170, 175, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 364, 1127, 1128, 1129, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1563, 1564, 1569, 1782, 1803, 1804, 2021, 2022, 2023, 3229, 3230, 3231, 3232, 3233, 3234, 3247, 3248, 3253, 3254, 3255, 3256, 3257, 3258, 3259, 3268, 3385, 3386, 3387, 3388, 3389, 3390, 3391, 3392, 3393, 3394, 3395, 3396, ...]}

In [27]:
## We can prove the above by using the .head() method
## Notice rows 0-15 are "good" but 16, 18 and 19 are "moderate" this is backed up above by looking at the axis's listed
air_quality['PM2.5_category'].head(20)

0         Good
1         Good
2         Good
3         Good
4         Good
5         Good
6         Good
7         Good
8         Good
9         Good
10        Good
11        Good
12        Good
13        Good
14        Good
15        Good
16    Moderate
17        Good
18    Moderate
19    Moderate
Name: PM2.5_category, dtype: category
Categories (6, object): ['Good' < 'Moderate' < 'Unhealthy for sensitive groups' < 'Unhealthy' < 'Very unhealthy' < 'Hazardous']

In [34]:
## We can view all the group names by using the .keys() method
air_quality.groupby(by='PM2.5_category').groups.keys()

C:\Users\jakeb\AppData\Local\Temp\ipykernel_11152\2133361919.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  air_quality.groupby(by='PM2.5_category').groups.keys()

dict_keys(['Good', 'Moderate', 'Unhealthy for sensitive groups', 'Unhealthy', 'Very unhealthy', 'Hazardous'])

In [36]:
## We can view specifiec groups by using .get_group() method
air_quality.groupby(by='PM2.5_category').get_group('Good')

C:\Users\jakeb\AppData\Local\Temp\ipykernel_11152\1925879269.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  air_quality.groupby(by='PM2.5_category').get_group('Good')

,date_time,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,...,hour,quarter,day_of_week_num,day_of_week_name,time_until_2022,time_until_2022_days,time_until_2022_weeks,prior_2016_ind,PM2.5_category,TEMP_category
0,2013-03-01 00:00:00,9.0,9.0,3.0,17.0,300.0,89.0,-0.5,1024.5,-21.4,...,0,1,4,Friday,3228 days 00:00:00,3228.000000,461.142857,True,Good,Very Cold
1,2013-03-01 01:00:00,4.0,4.0,3.0,16.0,300.0,88.0,-0.7,1025.1,-22.1,...,1,1,4,Friday,3227 days 23:00:00,3227.958333,461.136905,True,Good,Very Cold
2,2013-03-01 05:00:00,4.0,4.0,9.0,25.0,300.0,78.0,-2.4,1027.5,-21.3,...,5,1,4,Friday,3227 days 19:00:00,3227.791667,461.113095,True,Good,Very Cold
3,2013-03-01 06:00:00,5.0,5.0,10.0,29.0,400.0,67.0,-2.5,1028.2,-20.4,...,6,1,4,Friday,3227 days 18:00:00,3227.750000,461.107143,True,Good,Very Cold
4,2013-03-01 07:00:00,3.0,6.0,12.0,40.0,400.0,52.0,-1.4,1029.5,-20.4,...,7,1,4,Friday,3227 days 17:00:00,3227.708333,461.101190,True,Good,Very Cold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95676,2017-02-28 11:00:00,7.0,18.0,3.0,23.0,400.0,82.0,13.3,1016.0,-12.8,...,11,1,1,Tuesday,1767 days 13:00:00,1767.541667,252.505952,False,Good,Warm
95677,2017-02-28 12:00:00,8.0,17.0,2.0,19.0,300.0,87.0,12.9,1015.4,-14.9,...,12,1,1,Tuesday,1767 days 12:00:00,1767.500000,252.500000,False,Good,Warm
95678,2017-02-28 13:00:00,6.0,8.0,2.0,18.0,300.0,89.0,14.0,1014.5,-15.0,...,13,1,1,Tuesday,1767 days 11:00:00,1767.458333,252.494048,False,Good,Warm
95680,2017-02-28 15:00:00,9.0,9.0,2.0,22.0,300.0,91.0,15.4,1013.0,-15.0,...,15,1,1,Tuesday,1767 days 09:00:00,1767.375000,252.482143,False,Good,Warm
95681,2017-02-28 16:00:00,10.0,29.0,3.0,21.0,300.0,94.0,14.9,1012.6,-15.4,...,16,1,1,Tuesday,1767 days 08:00:00,1767.333333,252.476190,False,Good,Warm

## Stats Methods and groupby()

In [44]:
## We can apply groupby() after sorting data
air_quality.sort_values('date_time').groupby(by = 'year')

In [46]:
## We can then use the first() to get the first records in each group. Basically the earliest records in each year since their sorted
air_quality.sort_values('date_time').groupby(by = 'year').first()

,date_time,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,...,hour,quarter,day_of_week_num,day_of_week_name,time_until_2022,time_until_2022_days,time_until_2022_weeks,prior_2016_ind,PM2.5_category,TEMP_category
year,,,,,,,,,,,,,,,,,,,,,
2013,2013-03-01 00:00:00,9.0,9.0,3.0,17.0,300.0,89.0,-0.5,1024.5,-21.4,...,0,1,4,Friday,3228 days 00:00:00,3228.000000,461.142857,True,Good,Very Cold
2014,2014-01-01 01:00:00,66.0,154.0,40.0,81.0,1500.0,7.0,-1.1,1008.8,-13.0,...,1,1,2,Wednesday,2921 days 23:00:00,2921.958333,417.422619,True,Unhealthy,Very Cold
2015,2015-01-01 00:00:00,3.0,14.0,15.0,29.0,600.0,33.0,-7.0,1026.0,-23.8,...,0,1,3,Thursday,2557 days 00:00:00,2557.000000,365.285714,True,Good,Very Cold
2016,2016-01-01 00:00:00,200.0,209.0,31.0,98.0,3400.0,2.0,-2.5,1024.5,-8.2,...,0,1,4,Friday,2192 days 00:00:00,2192.000000,313.142857,False,Very unhealthy,Very Cold
2017,2017-01-01 00:00:00,423.0,509.0,5.0,102.0,5900.0,2.0,-4.7,1022.1,-6.1,...,0,1,6,Sunday,1826 days 00:00:00,1826.000000,260.857143,False,Hazardous,Very Cold